### ISSUE TITLE
igmpproxy

### ISSUE THREAD

**Issue by itobi1** [zocker007/G110-USS-Arduino#1]
Hey @zocker007,

nicht wundern, dass ich dich hierüber kontaktiere. In deinem igmpproxy repo kann ich leider keine issues erstellen.

Ich würde gerne deine abgeänderte Version des igmpproxy nutzen, da ich den Client-Support für das IPTV der Telekom benötige.
Kannst du mir kurz erklären, wie ich dies tun kann? Ich bin leider nicht so der Profi im Umgang mit C-Programmen :D

Danke und viele Grüße
itobi1

**Comment by zocker007** [comment]
igmpproxy wird mit GNU autotools gebaut. Du musst den Branch implement-source-specific-multicast aus meinem Repo auschecken und bauen. Wie hast du denn vor igmpproxy einzusetzen?
Ich habe im Repo mal Discussions zugelassen kannst du mal eine dazu starten? Dann kann ich das Issue hier zumachen.
